stages:
  - build
  - test
  - deploy

variables:
  # RAKE_COMMAND is for deploy jobs
  RAKE_COMMAND: sudo -u $RAILS_USER -n -i $RAILS_ROOT/bin/rake -f $RAILS_ROOT/Rakefile

build_job:
  stage: build
  before_script:
    - ruby -v
    - gem install bundler -N
    - bundle version
  script:
    # Post-migration: set RAILS_DEPLOY_PATH=/opt/morphosource
    - cp /opt/morphosource/etc/database.yml config/
    - cp /opt/morphosource/etc/analytics.yml config/
    - bundle install --path=vendor/bundle --without=development --binstubs=bin --no-cache
    - bundle binstubs bundler --force
    - bundle exec rake assets:precompile
  artifacts:
    paths:
      - .bundle/
      - bin/
      - config/database.yml
      - config/analytics.yml
      - public/assets/
      - vendor/bundle/
  tags:
    - build

test_job:
  stage: test
  allow_failure: true
  variables:
    RAILS_ENV: test
    DATABASE_URL: $TEST_DATABASE_URL
  before_script:
    - ruby -v
    - bundle version
    - node -v
    - psql --version
    - $FITS_PATH -v
    - $BLENDER_PATH/blender -v
    - img2dcm --version
    - dcmdjpeg --version
    - gltf-pipeline --version
  script:
    - bin/rake db:reset ci
  tags:
    - test

deploy_dev:
  environment:
    name: development
    url: https://morphosource-dev.lib.duke.edu/
  stage: deploy
  script: &deploy_script
    - rsync -rl --delete --exclude-from=EXCLUDE ./ $RAILS_ROOT/
    - '$RAKE_COMMAND db:setup || true'
    - $RAKE_COMMAND db:migrate
    - $RAKE_COMMAND tmp:cache:clear
    - $RAKE_COMMAND hyrax:workflow:load
  after_script: &after_deploy
    - sudo /usr/bin/systemctl restart $RAILS_SERVICE_UNIT
  only:
    - dev
  tags:
    - development

deploy_demo:
  stage: deploy
  environment:
    name: demo
    url: https://morphosource-demo.lib.duke.edu/
  script: *deploy_script
  after_script: *after_deploy
  only:
    - dev
  tags:
    - demo
