test:
  stage: test
  before_script:
    - $RAILS_DEPLOY_PATH/bin/before_test.sh
  script:
    - $RAILS_DEPLOY_PATH/bin/test.sh
  after_script:
    - $RAILS_DEPLOY_PATH/bin/after_test.sh

deploy_dev:
  environment:
    name: development
    url: https://morphosource-dev.lib.duke.edu/
  stage: deploy
  script:
    - $RAILS_DEPLOY_PATH/bin/deploy.sh $CI_PROJECT_DIR
  after_script:
    - $RAILS_DEPLOY_PATH/bin/after_deploy.sh
  only:
    - dev
  tags:
    - development
