stages:
  - build
  - test
  - deploy

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

variables:
  APP_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build_job:
  stage: build
  before_script:
    - docker info
  script:
    - docker build --pull -f $MORPHOSOURCE_HOME/Dockerfile -t $APP_IMAGE .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $APP_IMAGE
  only:
    - docker
  tags:
    - build
    - docker

test_job:
  stage: test
  variables:
    COMPOSE_FILE: $MORPHOSOURCE_HOME/docker-compose.test.yml
  before_script:
    - docker info
    - docker-compose version
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $APP_IMAGE
    - docker-compose up --exit-code-from app
  after_script:
    - docker-compose down
  only:
    - docker
  tags:
    - test
    - docker

deploy_dev:
  environment:
    name: development
    url: https://morphosource-dev.lib.duke.edu/
  stage: deploy
  before_script:
    - docker info
    - docker-compose version
    - 'env | sort'
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $APP_IMAGE
    - sudo systemctl restart docker-compose@morphosource.service
  only:
    # - dev
    - docker
  tags:
    # - development
    - docker
