# Based on https://github.com/duke-libraries/rdr/blob/develop/.travis.yml

language: ruby
rvm:
  - 2.4.2
services:
  - postgresql
  # Use redis for background jobs
  - redis-server
addons:
  firefox: '61.0'
before_install:
  # from http://www.columbia.edu/~njn2118/journal/2016/10/28.html
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.21.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  # begin FITS setup
  - mkdir $TRAVIS_BUILD_DIR/download
  - cd $TRAVIS_BUILD_DIR/download
  - export FITSVERSION=1.3.0
  - curl http://projects.iq.harvard.edu/files/fits/files/fits-$FITSVERSION.zip -o fits.zip
  - mkdir fits-$FITSVERSION
  - unzip fits.zip -d fits-$FITSVERSION
  - chmod a+x fits-$FITSVERSION/*.sh
  - wget https://github.com/MorphoSource/morphosource-vagrant/blob/master/install_scripts/fits_config/fits.xml
  - wget https://github.com/MorphoSource/morphosource-vagrant/blob/master/install_scripts/fits_config/exiftool/exiftool_dicom_to_fits.xslt
  - wget https://github.com/MorphoSource/morphosource-vagrant/blob/master/install_scripts/fits_config/exiftool/exiftool_xslt_map.xml
  - cp fits.xml fits-$FITSVERSION/xml/.
  - more /home/travis/build/MorphoSource/MorphoSource_SF/download/fits-1.3.0/xml/fits.xml
  - cp exiftool_dicom_to_fits.xslt fits-$FITSVERSION/xml/exiftool/.
  - cp exiftool_xslt_map.xml fits-$FITSVERSION/xml/exiftool/.
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/download/fits-$FITSVERSION
  - fits.sh -v
  - fits.sh -i "/home/travis/build/MorphoSource/MorphoSource_SF/spec/fixtures/CMB06020_R-m1_011.dcm"
  # end FITS setup
  - cd $TRAVIS_BUILD_DIR/MorphoSource_SF
before_script:
  - "cp .rspec.travis .rspec"
  # Don't need to use role_map if using hydra-role-manager
  # - "cp config/role_map.yml.sample config/role_map.yml"
  - "cp spec/travis_spec_helper.rb spec/spec_helper.rb"
  # Sets up test db name to be travis_ci_test
  - "cp config/database.yml.travis config/database.yml"
  - "psql -c 'create database travis_ci_test;' -U postgres"

script: "bundle exec rake ci"
jdk:
  - oraclejdk8
