# config/authorities/modalities.yml
# URI for terms list: https://www.idigbio.org/wiki/index.php/3D_Scan_Modality_Subtypes
terms:
  - id: MicroNanoXRayComputedTomography
    term: Micro/Nano X-Ray Computed Tomography (micro/nanoCT)
    active: true
  - id: MedicalXRayComputedTomography
    term: Medical X-Ray Computed Tomography (CT)
    active: true
  - id: MagneticResonanceImaging
    term: Magnetic Resonance Imaging (MRI)
    active: true
  - id: PositronEmissionTomography
    term: Positron Emission Tomography (PET)
    active: true
  - id: SynchrotronImaging
    term: Synchrotron Imaging
    active: true
  - id: NeutrinoImaging
    term: Neutrino Imaging
    active: true
  - id: Photogrammetry
    term: Photogrammetry
    active: true
  - id: StructuredLight
    term: Structured Light
    active: true
  - id: LaserScan
    term: Laser Scan
    active: true
  - id: ConfocalImageStacking
    term: Confocal Image Stacking
    active: true
  - id: Infrared
    term: Infrared
    active: true
  - id: ReflectanceTransformationImaging
    term: Reflectance Transformation Imaging
    active: true
  - id: Photography
    term: Photography
    active: true
  - id: ScanningElectronMicroscopy
    term: Scanning Electron Microscopy
    active: true
