module Hydra::Works::Characterization
  class DicomSchema < ActiveTriples::Schema
    property :spacing_between_slices, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#SpacingBetweenSlices')
    property :modality, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#Modality')
    property :secondary_capture_device_manufacturer, predicate: RDF::URI('https://www.morphosource.org/terms/dicomSecondaryCaptureDeviceManufacturer')
    property :secondary_capture_device_software_vers, predicate: RDF::URI('https://www.morphosource.org/terms/dicomSecondaryCaptureDeviceSoftwareVers')
    property :file_type_extension, predicate: RDF::URI('https://www.morphosource.org/terms/dicomFileTypeExtension')
    property :image_type, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#ImageType')
    property :study_date, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#StudyDate')
    property :series_date, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#SeriesDate')
    property :content_date, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#ContentDate')
    property :study_time, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#StudyTime')
    property :series_time, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#SeriesTime')
    property :content_time, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#ContentTime')
    property :accession_number, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#AccessionNumber')
    property :instance_number, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#InstanceNumber')
    property :image_position_patient, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#ImagePositionPatient')
    property :image_orientation_patient, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#ImageOrientationPatient')
    property :samples_per_pixel, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#SamplesPerPixel')
    property :photometric_interpretation, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#PhotometricInterpretation')
    property :rows, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#Rows')
    property :columns, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#Columns')
    property :pixel_spacing, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#PixelSpacing')
    property :bits_allocated, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#BitsAllocated')
    property :bits_stored, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#BitsStored')
    property :high_bit, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#HighBit')
    property :pixel_representation, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#PixelRepresentation')
    property :window_center, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#WindowCenter')
    property :window_width, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#WindowWidth')
    property :rescale_intercept, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#RescaleIntercept')
    property :rescale_slope, predicate: RDF::URI('http://purl.org/healthcarevocab/v1#RescaleSlope')
    property :window_center_and_width_explanation, predicate: RDF::URI('https://www.morphosource.org/terms/dicomWindowCenterAndWidthExplanation')
  end
end
