# Generated by hyrax:models:install
class FileSet < ActiveFedora::Base

  include ::Hyrax::FileSetBehavior

  self.indexer = ::MsFileSetIndexer

  # for images
  delegate(:bits_per_sample, to: :characterization_proxy)

  # for dicom
  delegate(:spacing_between_slices, 
            :modality,
            :secondary_capture_device_manufacturer,
            :secondary_capture_device_software_vers,
            to: :characterization_proxy)

end